name: Run Playwright Tests

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name to run tests on'
        required: true
        default: 'main'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright Browsers
      run: |
        playwright install

    - name: Install Allure Commandline
      run: |
        curl -sL https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.tgz | tar xz -C /usr/local/bin
        ln -s /usr/local/bin/allure-2.21.0/bin/allure /usr/local/bin/allure

    - name: Clean up previous Allure and HTML reports
      run: |
        rm -rf test/tests/artifacts/allure_report test/tests/artifacts/html/html_report.html

    - name: Run tests
      run: |
        pytest

    - name: Generate Allure Report
      run: |
        allure generate test/tests/artifacts/allure_report --clean -o test/tests/artifacts/allure_report

    - name: Upload Allure Report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: test/tests/artifacts/allure_report

    - name: Upload Allure Report
      uses: actions/upload-artifact@v3
      with:
        name: combine-allure-report
        path: test/tests/artifacts/combine_allure_report

    - name: Upload HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: html-report
        path: test/tests/artifacts/html
