name: Run Pytest and Generate Allure Report

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name to run tests on'
        required: true
        default: 'main'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Java
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright Browsers
      run: |
        npm install -g playwright
        npx playwright install

    - name: Install Xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb

    - name: Run tests with Xvfb
      run: |
        xvfb-run -a pytest --alluredir=allure-results

    - name: Download Allure Commandline
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.17.0/allure-2.17.0.tgz
        tar -xzf allure-2.17.0.tgz
        sudo mv allure-2.17.0/bin/allure /usr/local/bin/allure

    - name: Verify Allure Installation
      run: |
        allure --version

    - name: Generate Allure report
      run: |
        allure generate allure-results --clean -o allure-report

    - name: Upload Allure report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report
